version: '3.1'

volumes:
  pg_project:

services:
  bot:
    build: ./
    command: ./bot
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "6666:5432"
    env_file:
      - .env
